apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: regapp
spec:
  selector:
    app: regapp
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8080
  type: {{ .Values.service.type }}
